package common

trait TestConfig {

  val GAMESERVER_SPEC_SERVER_PORT = 8080
  val CLIENT_SPEC_SERVER_PORT = 8081
  val HTTP_CLIENT_SPEC_SERVER_PORT = 8082
  val SERVER_ACTOR_SPEC_PORT = 8083
  val CORE_CLIENT_SPEC_SERVER_PORT = 8084
  val SOCKET_HANDLER_SPEC_SERVER_PORT = 8085


}
